version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school_management_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - school_management
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    container_name: school_management_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - school_management
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: school_management_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3307:3306"
    networks:
      - school_management

  redis:
    image: redis:alpine
    container_name: school_management_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - school_management

  node:
    image: node:18-alpine
    container_name: school_management_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - school_management

networks:
  school_management:
    driver: bridge

volumes:
  dbdata:
    driver: local
