version: '3.8'

services:
  # PHP-FPM Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school_manager_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    networks:
      - school_manager_network
    depends_on:
      - db
      - redis

  # Nginx Web Server
  web:
    image: nginx:alpine
    container_name: school_manager_web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - school_manager_network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: school_manager_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - school_manager_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: school_manager_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - school_manager_network

  # Node for Frontend Build
  node:
    image: node:20-alpine
    container_name: school_manager_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"
    networks:
      - school_manager_network

networks:
  school_manager_network:
    driver: bridge

volumes:
  db_data:
    driver: local
